### ISSUE TITLE
Add a block that links to Eventbrite for purchasing a ticket

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#134]
This task first needs that we configure EventBrite.

**Comment by samuelsolis** [comment]
I just created 2 code block linked to the eventbrite form:
 - The first has the same structure that the proposal session block, to theme in using similar style.
 - The second one is a little button to theme it fixed in the bottom right corner following the style guidelines (https://projects.invisionapp.com/boards/V233TLCG5W4KU/). Hide it in mobile versions.

 - We can create (directly in production) a menu item linked to the eventbrite form after launch this issue.

All changes are in #134-ticketBlock

**Comment by isholgueras** [comment]
I added styles to frontpage block and floating-button.

I moved floating-button from frontpage.twig to page.twig to show Buy tickets button on every page.

Ready in branch 134

**Comment by juampynr** [comment]
Done.
