### ISSUE TITLE
Homepage performance

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#136]
Let's get a 90/100 at https://developers.google.com for mobile and desktop.

**Comment by juampynr** [comment]
![image](https://cloud.githubusercontent.com/assets/108130/24331889/776ae87a-123d-11e7-9ba8-73243d1e6207.png)

![image](https://cloud.githubusercontent.com/assets/108130/24331901/9d497c96-123d-11e7-9fb7-23d51269f453.png)

**Comment by juampynr** [comment]
For JS/CSS aggregation, looks like https://www.drupal.org/project/advagg can help us. As for image compression, https://www.drupal.org/project/imageapi_optimize.

I will try these modules locally with the Page Speed browser extension.

@NITEMAN, have you heard of the above modules? Any suggestions to improve overall performance?

**Comment by NITEMAN** [comment]
I've reviewed the analysis: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2F2017.drupalcamp.es%2F

There are a couple of things that we van do server side (notably SVG gzip compression), but I fear we have more important/urgent things rather than focusing on performance.

Regarding the modules you mention:
* ADVAGG: We use advagg in almost all D<8 sites, but at the moment in no D8 site.
* IMAGEAPI_PPTIMIZE: We are considering it in Axel, but we haven't tried it yet

**Comment by keopx** [comment]
FYI ADVAGG bug with Drupal 8.3.0 https://www.drupal.org/node/2850263

**Comment by juampynr** [comment]
The site performed very well. There was no need to do any optimizations.
