### ISSUE TITLE
Deploy/config is still broken

### ISSUE THREAD

**Issue by NITEMAN** [AsociacionDrupalES/DrupalCampSpain#23]
Config import is failing. Log:
~~~
drush cim sync -y 
 Collection   Config                                     Operation                
              block.block.landinginfowithcountdownblock  create 
              block.block.mainpagecontent                create 
              core.extension                             update 
              language.negotiation                       update 
              features.settings                          delete   
              features.bundle.default                    delete   
 language.es  views.view.block_content                   update 
 language.es  views.view.content                         update 
 language.es  views.view.files                           update 
 language.es  views.view.frontpage                       update 
 language.es  views.view.user_admin_people               update 
 language.es  core.date_format.html_year                 delete
Import the listed configuration changes? (y/n): y
exception 'Drupal\Component\Plugin\Exception\PluginNotFoundException' with message 'The "features_bundle" entity type does not exist.' in                           [error]
/var/www/dev.drupalcamp.es/releases/20160919104524Z/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php:125
Stack trace:
#0 /var/www/dev.drupalcamp.es/releases/20160919104524Z/web/core/lib/Drupal/Core/Entity/EntityManager.php(44):
Drupal\Core\Entity\EntityTypeManager->getDefinition('features_bundle', true)
#1 /var/www/dev.drupalcamp.es/releases/20160919104524Z/web/core/lib/Drupal/Core/Entity/Event/BundleConfigImportValidate.php(54):
Drupal\Core\Entity\EntityManager->getDefinition('features_bundle')
#2 /var/www/dev.drupalcamp.es/releases/20160919104524Z/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111):
Drupal\Core\Entity\Event\BundleConfigImportValidate->onConfigImporterValidate(Object(Drupal\Core\Config\ConfigImporterEvent), 'config.importer...',
Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#3 /var/www/dev.drupalcamp.es/releases/20160919104524Z/web/core/lib/Drupal/Core/Config/ConfigImporter.php(726):
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('config.importer...', Object(Drupal\Core\Config\ConfigImporterEvent))
#4 /var/www/dev.drupalcamp.es/releases/20160919104524Z/web/core/lib/Drupal/Core/Config/ConfigImporter.php(513): Drupal\Core\Config\ConfigImporter->validate()
#5 /var/www/dev.drupalcamp.es/releases/20160919104524Z/web/core/lib/Drupal/Core/Config/ConfigImporter.php(459): Drupal\Core\Config\ConfigImporter->initialize()
#6 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/commands/core/config.drush.inc(715): Drupal\Core\Config\ConfigImporter->import()
#7 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/includes/drush.inc(725): _drush_config_import(Object(Drupal\Core\Config\StorageComparer))
#8 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('_drush_config_i...', Array)
#9 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/commands/core/config.drush.inc(693): drush_op('_drush_config_i...',
Object(Drupal\Core\Config\StorageComparer))
#10 [internal function]: drush_config_import('sync')
#11 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/includes/command.inc(373): call_user_func_array('drush_config_im...', Array)
#12 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/includes/command.inc(224): _drush_invoke_hooks(Array, Array)
#13 [internal function]: drush_command('sync')
#14 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/includes/command.inc(192): call_user_func_array('drush_command', Array)
#15 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#16 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#17 /var/www/dev.drupalcamp.es/releases/20160919104524Z/vendor/drush/drush/drush.php(12): drush_main()
#18 {main}
~~~

cc @juampynr @nuez

**Comment by nuez** [comment]
My guess is that you're importing stale configuration from the 'sync' folder in `sites/default/files/config.../sync` which is not part of the repository.

Try to import config from the /config directory. 

e.g. set  `$config_directories['repo'] = '../config';` in settings.local.php and run

drush cim repo -y

**Comment by NITEMAN** [comment]
That's not the case, settings.local.php contains:
~~~
$config_directories['sync'] = '../config';
~~~

If if have to guess I suppose there's a module that was removed along with it's config and drupal can't remove the config since the code is not present any more.

I think @jonhattan can explain it more clearly

**Comment by nuez** [comment]
The way it is working currently, the configuration in `sites/default/files` is not part of the repository (.gitignore), so what you're trying to deploy is effectively stale configuration. As far as I understand, with the approach we have, it only serves the purpose of comparing the active configuration saved in the database to the configuration imported from the /config/ folder in the root of the project.

If we wan't to be able to 'force deploy' configuration YML files, we need to save them somewhere that's not` sites/default/files`, instead, as suggested by @juampynr original commit, in the root folder called `config`.

If we're always going to force configuration from the repository, we could possible remove the `sites/default/files/config...` directory all together or point the 'sync' config directory in `settings.php` directly to the `../config` root folder (although that would be risking accidentally overwriting the configuration by eg. `drush cex` . 

In any case, in order to deploy configuration, we need to run `drush cim <path/to/config>` where path to config currently is the folder `/config/` in the project root.

**Comment by NITEMAN** [comment]
@nuez forget about `sites/default/files` that path is not relevant for our case. There's no need to mess with `sites/default/files/config`.

We are forcing config deployment from the very beginning (using `config` folder on repository's root).

We are running `drush cim sync -y` and `drush cr` as an integral part of our deployment workflow so `config` should contain allways an importable config

**Comment by nuez** [comment]
You're right, I misread your comment, 

In that case I don't know what could be the issue, I can't find features_bundle anywhere in the ../config, and I'm not getting the same issue even after a clean install. I'll have a look at it tomorrow.

**Comment by NITEMAN** [comment]
I think I've faced before this kind of errors, usually there was a point in time when some config was added (either via config dir or via module install) and the dependant code was removed from the repository before actually deleting the config so drush fails to delete the config.

**Comment by nuez** [comment]
I think I know what the issue is: Sometimes the configuration manager requieres the presence of the module in order to remove a dependency. So the configuration should be updated and imported first before fysically removing the module.

Other scenarios I can think of are dependencies through configurations that are required when processing the Configuration Import, before that dependency is actually removed by the Configuration Mananager

In any case: I think the problem solves itself by executing drush cim various times.

**Comment by nuez** [comment]
I think it must have something to do with that: 

The config-import is iterating over configuration that requires certain modules or dependencies, that are not removed until later in the execution queue of that same config-import. That's why my guess is to execute drush cim several times.

I've tried on localhost to 'purge' older configuration in the database by running `drush cim` several times until all errors disappear. (up to 3 times). That seems to work. Let me know if that works for you.

**Comment by NITEMAN** [comment]
@nuez runing `drush cim sync` multiple times doesn't resolve the issue

**Comment by nuez** [comment]
@NITEMAN In that case the only solutions I can think of are:

- Put features back into composer.json for the time being
- hook_update_N to remove the dependency directly from the database (don't know where (state system.module.files?))
- try drush cim sync --skip-modules=features

what do you think?

**Comment by juampynr** [comment]
@nuez make any changes that you need please. I tried to install the site locally following the README and I get warnings saying that config_installer does not exist.

**Comment by juampynr** [comment]
We should get to a point where following the installation steps gives us a working site with the landing page as the home.

**Comment by nuez** [comment]
Please see #25 for updated instructions and revised dependencies. I've added features back to composer.json although this wouldn't be necessary for a clean install, but is to fix the problem of the missing dependency on` drush cim`

**Comment by NITEMAN** [comment]
Now it works as expected
