### ISSUE TITLE
Promote schedule

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#261]
Just before and during drupalcamp, many people will open the website and navigate to the schedule.

@wildwildweb, how can we make the schedule as easy to reach as possible?

**Comment by wildwildweb** [comment]
We can use the "Come to drupalcamp block" and change for something like:
<img width="1341" alt="captura de pantalla 2017-04-26 a las 13 50 35" src="https://cloud.githubusercontent.com/assets/592608/25431168/2658a536-2a88-11e7-8d04-2ec7270e3dc1.png">

"PLAN YOUR DRUPALCAMP"
Check out sessions and speaker and don't miss your favorite... 

and in the CTA button: "Schedule" or "View Schedule"

We don't need this block anymore since we have the full width sticky "Buy tickets" CTA so i think could be a good solution.

**Comment by juampynr** [comment]
I like that!

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/265
