### ISSUE TITLE
Setup the homepage

### ISSUE THREAD

**Issue by nuez** [AsociacionDrupalES/DrupalCampSpain#66]

**Comment by nuez** [comment]
We need to think about the approach for the home page:

- static content
- views
- nodes / fields

Considering the website is cached, I'm inclined to go for a static content approach: a simple router for the homepage with a custom page--home.twig.html with the content, maybe some dynamic views such as the 'ponentes'

What do you think @juampynr @samuelsolis ?

**Comment by juampynr** [comment]
Looking at https://projects.invisionapp.com/share/D99TIIGHR#/screens, we have the following sections:

What | How
------------ | -------------
Welcome (@wildwildweb, the slogan is Short'N Sweet, can we change it? If it is text, then no problem). - static | Static block
Speakers | View block
Submit your session | Static block
Venue | Static block
Sponsors | View
Newsletter | Block
Footer | Block

Since we have a mix of blocks, what would be the easiest way to manage them? If Paragraphs is easy, then go for it. Otherwise, I am okay with a custom route where we place each block.

**Comment by samuelsolis** [comment]
I don't have experience with Paragraphs and I don't know how to works but if it's a nice solution... it's ok!

Maybe the custom route to place the block will be easier... for me both options are ok. I'm going to create an issue for each block (some of these already are created).

**Comment by nuez** [comment]
I think paragraphs is overkill for just one page. I would go for the router + hook_theme + custom twig with blocks. I'll assign this one to myself.

**Comment by juampynr** [comment]
OK @nuez! How can we help you?

**Comment by juampynr** [comment]
@nuez @samuelsolis, notice the list of milestones that I made: https://github.com/AsociacionDrupalES/DrupalCampSpain/milestones

Let's focus on reelasing 1.0 to production as soon as possible. I am here to help in any way I can but I am useless/slow/ignorant with front end stuff.

**Comment by nuez** [comment]
I think Newsletter, and everything underneath are general 'footer' blocks, that should be part of every page. 

In this issue we should solve:

- Sweet and short: part of twig template
- Dos días de charlas... part of twig template
- Ponentes confirmados: twig template + view
- Venue: The text could be a translatable block, the rest part of twig template
- Convertete en patrocinador: translatable custom block
- Business day: translatable block
- únete a la comunidad: translatable block
- sponsors: view with categories

**Comment by nuez** [comment]
@juampynr @samuelsolis see #78

**Comment by juampynr** [comment]
This is done. Let's continue with new issues/PRs.

**Comment by juampynr** [comment]
Here is an example of how it looks now https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/90#issuecomment-284321172
